import React, { useState } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { UploadCloud, FileText, X, ScanText, Settings, Copy, CheckCircle2, Download } from 'lucide-react';
import { upload } from '@vercel/blob/client';

export default function OcrPdf() {
  const [file, setFile] = useState(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [extractedText, setExtractedText] = useState('');
  const [copied, setCopied] = useState(false);

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      setFile(selectedFile);
      setExtractedText('');
    } else {
      alert("Please upload a valid PDF file.");
    }
  };

  const removeFile = () => {
    setFile(null);
    setExtractedText('');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(extractedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadTextFile = () => {
    const blob = new Blob([extractedText], { type: 'text/plain' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `MasterPdf_OCR_${file.name.split('.')[0]}.txt`;
    link.click();
  };

  const performOcr = async () => {
    if (!file) return;
    setIsProcessing(true);
    
    try {
      // 1. Upload to Vercel Blob
      const blob = await upload(file.name, file, { access: 'public', handleUploadUrl: '/api/upload' });

      // 2. Send request to backend for OCR / Text Extraction
      const response = await fetch('/api/master-convert', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'ocr-pdf', fileUrl: blob.url }),
      });
      
      const data = await response.json();
      
      if (response.ok && data.downloadUrl) {
        // Fetch the raw text file generated by the backend
        const textResponse = await fetch(data.downloadUrl);
        const textContent = await textResponse.text();
        setExtractedText(textContent || "No text could be found or extracted from this document.");
      } else {
        alert(data.error || "OCR processing failed.");
      }
    } catch (error) {
      alert("Server connection failed.");
    }
    setIsProcessing(false);
  };

  return (
    <div className="min-h-screen flex flex-col font-sans bg-[#F5F5F7]">
      <Head>
        <title>OCR PDF online - Extract text from scanned PDFs - MasterPdf</title>
      </Head>
      <Navbar />

      <main className="flex-grow flex flex-col items-center justify-center p-6 mt-16">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-yellow-100 text-yellow-800 px-3 py-1 rounded-full text-xs font-bold mb-4">
            <ScanText size={14} /> Text Recognition
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4 tracking-tight">OCR PDF</h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Easily convert scanned PDF documents into searchable, selectable, and editable text.
          </p>
        </div>

        <div className="w-full max-w-6xl bg-white rounded-2xl shadow-sm border border-gray-200 p-8 min-h-[500px] flex flex-col items-center justify-center relative">
          {!file ? (
            <div className="text-center w-full">
              <input type="file" id="file-upload" accept=".pdf" onChange={handleFileChange} className="hidden" />
              <label htmlFor="file-upload" className="cursor-pointer bg-[#E5322D] hover:bg-red-700 text-white text-xl font-bold py-6 px-12 rounded-xl inline-flex items-center gap-3 transition shadow-lg hover:shadow-xl transform hover:-translate-y-1">
                <UploadCloud size={28} /> Select Scanned PDF
              </label>
            </div>
          ) : (
            <div className="w-full h-full flex flex-col md:flex-row gap-8 items-start pt-4">
              
              {/* Left Side: Setup */}
              <div className="w-full md:w-1/3 flex flex-col h-[450px] justify-between bg-gray-50 border border-gray-200 rounded-lg p-6 relative">
                <button onClick={removeFile} className="absolute top-4 right-4 bg-white border border-gray-200 text-gray-500 hover:text-red-500 rounded-full p-2 shadow-sm transition">
                  <X size={20} />
                </button>
                
                <div className="flex flex-col items-center mt-6">
                  <FileText size={70} className="text-[#E5322D] mb-4 opacity-90" />
                  <p className="text-sm text-gray-800 font-bold text-center break-words w-full px-2">{file.name}</p>
                </div>

                <div className="bg-white p-4 rounded-lg border border-gray-200 mt-6 shadow-sm">
                  <p className="text-xs font-bold text-gray-700 mb-1">OCR Engine Settings</p>
                  <p className="text-[11px] text-gray-500">Document will be scanned for text layout and character recognition automatically.</p>
                </div>

                <button 
                  onClick={performOcr} 
                  disabled={isProcessing || extractedText} 
                  className="w-full mt-6 flex items-center justify-center gap-2 px-4 py-4 rounded-xl text-white font-bold text-sm transition shadow-md bg-yellow-500 hover:bg-yellow-600 disabled:bg-gray-400"
                >
                  {isProcessing ? <><Settings className="animate-spin" size={18} /> Scanning Document...</> : <>Extract Text <ScanText size={18} /></>}
                </button>
              </div>

              {/* Right Side: OCR Output */}
              <div className="w-full md:w-2/3 flex flex-col h-[450px]">
                <div className="flex justify-between items-center mb-4 border-b pb-2">
                  <h3 className="text-xl font-bold text-gray-900">Extracted Text</h3>
                  {extractedText && (
                    <div className="flex gap-3">
                      <button onClick={handleCopy} className="flex items-center gap-1 text-sm font-semibold text-gray-600 hover:text-[#E5322D] transition">
                        {copied ? <><CheckCircle2 size={16} className="text-green-500"/> Copied!</> : <><Copy size={16}/> Copy</>}
                      </button>
                      <button onClick={downloadTextFile} className="flex items-center gap-1 text-sm font-semibold text-white bg-gray-800 px-3 py-1 rounded hover:bg-black transition">
                        <Download size={16}/> Save .txt
                      </button>
                    </div>
                  )}
                </div>
                
                <div className="flex-grow bg-white border border-gray-200 rounded-xl p-6 overflow-y-auto shadow-inner">
                  {!extractedText ? (
                    <div className="h-full flex flex-col items-center justify-center text-gray-400">
                      <ScanText size={50} className="mb-4 opacity-30" />
                      <p className="text-sm font-medium">Click "Extract Text" to run OCR on your document.</p>
                    </div>
                  ) : (
                    <textarea 
                      className="w-full h-full resize-none outline-none text-gray-800 text-[14px] leading-relaxed font-mono"
                      value={extractedText}
                      onChange={(e) => setExtractedText(e.target.value)}
                    />
                  )}
                </div>
              </div>

            </div>
          )}
        </div>
      </main>

      <Footer />
    </div>
  );
}
