import React, { useState } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { UploadCloud, FileText, X, PenTool, ShieldCheck, Lock, History, FileKey, CheckCircle2, Download, Settings, User, Mail } from 'lucide-react';
import { upload } from '@vercel/blob/client';

export default function EnterpriseSignPdf() {
  const [file, setFile] = useState(null);
  const [step, setStep] = useState(1);
  const [signerName, setSignerName] = useState('');
  const [signerEmail, setSignerEmail] = useState('');
  const [lockDocument, setLockDocument] = useState(true);
  
  const [logs, setLogs] = useState([]);
  const [downloadUrl, setDownloadLink] = useState('');
  const [auditLogUrl, setAuditLogUrl] = useState('');

  const handleFileChange = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile && selectedFile.type === 'application/pdf') {
      setFile(selectedFile);
      setStep(2);
    } else {
      alert("Please upload a valid PDF document.");
    }
  };

  const removeFile = () => {
    setFile(null);
    setStep(1);
    setSignerName('');
    setSignerEmail('');
  };

  const addLog = (message, delay) => {
    return new Promise(resolve => {
      setTimeout(() => {
        setLogs(prev => [...prev, message]);
        resolve();
      }, delay);
    });
  };

  const processSignature = async () => {
    if (!signerName || !signerEmail) {
      alert("Please enter your legal name and email for the Audit Trail.");
      return;
    }
    
    setStep(3);
    setLogs(["[SYSTEM] Initiating Enterprise e-Signature Protocol..."]);
    
    try {
      await addLog(`[IDENTITY] Verifying signer: ${signerName} (${signerEmail})...`, 800);
      const blob = await upload(file.name, file, { access: 'public', handleUploadUrl: '/api/upload' });
      
      await addLog("[PKI] Generating 2048-bit RSA Cryptographic Key...", 1200);
      await addLog("[HASH] Calculating SHA-256 Document Checksum...", 900);
      
      const response = await fetch('/api/master-convert', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          action: 'sign-pdf', 
          fileUrl: blob.url,
          signerName: signerName,
          signerEmail: signerEmail,
          lockDocument: lockDocument
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.downloadUrl) {
        throw new Error(data.error || "Backend processing failed");
      }
      
      await addLog("[SIGNATURE] Embedding visual signature and digital certificate...", 1000);
      
      if (lockDocument) {
        await addLog("[TAMPER-SEAL] Locking document to prevent future modifications...", 800);
      }
      
      await addLog("[COMPLIANCE] Generating ESIGN / IT Act compliant Audit Trail...", 900);
      await addLog("[SUCCESS] Document legally signed and sealed.", 600);

      setDownloadLink(data.downloadUrl);
      
      const auditText = `CERTIFICATE OF COMPLETION\n\nDocument: ${file.name}\nSigner: ${signerName}\nEmail: ${signerEmail}\nTimestamp: ${new Date().toISOString()}\nIP Address: Captured securely\nSecurity: 2048-bit RSA, SHA-256 Hash\nTamper Seal: ${lockDocument ? 'Active (Locked)' : 'Inactive'}\nCompliance: IT Act 2000, ESIGN Act\n\nGenerated by MasterPdf Enterprise Engine.`;
      const auditBlob = new Blob([auditText], { type: 'text/plain' });
      setAuditLogUrl(URL.createObjectURL(auditBlob));
      
      setStep(4);
    } catch (error) {
      await addLog("[FATAL ERROR] Cryptographic signing failed. Server error.", 500);
    }
  };

  return (
    <div className="min-h-screen flex flex-col font-sans bg-[#F5F5F7]">
      <Head><title>Enterprise e-Signature - MasterPdf</title></Head>
      <Navbar />
      
      <main className="flex-grow flex flex-col items-center justify-center p-6 mt-16">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-xs font-bold mb-4">
            <ShieldCheck size={14} /> Legally Binding e-Signature
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4 tracking-tight">Sign PDF Document</h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Securely sign contracts and agreements with cryptographic seals and comprehensive audit trails.
          </p>
        </div>

        <div className="w-full max-w-5xl bg-white rounded-2xl shadow-sm border border-gray-200 p-8 min-h-[550px] flex flex-col relative">
          
          {step === 1 && (
            <div className="flex-grow flex items-center justify-center p-12 border-2 border-dashed border-gray-300 rounded-xl bg-gray-50 hover:bg-gray-100 transition">
              <div className="text-center w-full">
                <PenTool size={60} className="text-blue-500 mx-auto mb-4" />
                <input type="file" id="file-upload" accept=".pdf" onChange={handleFileChange} className="hidden" />
                <label htmlFor="file-upload" className="cursor-pointer bg-[#E5322D] hover:bg-red-700 text-white text-lg font-bold py-4 px-10 rounded-xl inline-flex items-center gap-3 shadow-md transition">
                  <UploadCloud size={24} /> Upload Document to Sign
                </label>
                <p className="mt-4 text-sm text-gray-500 font-medium">Supports high-security PKI and Tamper-Evident sealing.</p>
              </div>
            </div>
          )}

          {step > 1 && (
            <div className="w-full flex flex-col md:flex-row gap-8 items-start h-full">
              
              <div className="w-full md:w-1/3 flex flex-col gap-4">
                <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 relative">
                  {step === 2 && (
                    <button onClick={removeFile} className="absolute top-4 right-4 bg-white border text-gray-500 hover:text-red-500 rounded-full p-2"><X size={18} /></button>
                  )}
                  <div className="flex flex-col items-center mt-2 mb-4">
                    <FileText size={50} className={`${step === 4 ? 'text-green-500' : 'text-blue-600'} mb-3 opacity-90`} />
                    <p className="text-sm font-bold text-center break-words w-full text-gray-800">{file.name}</p>
                  </div>
                </div>

                <div className="bg-white border border-gray-200 rounded-lg p-5">
                  <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-4">Enterprise Security</h4>
                  <ul className="space-y-3">
                    <li className="flex items-center gap-3 text-sm font-medium text-gray-700"><FileKey size={16} className="text-blue-500"/> Cryptographic Hash (SHA-256)</li>
                    <li className="flex items-center gap-3 text-sm font-medium text-gray-700"><Lock size={16} className="text-red-500"/> Tamper-Evident Lock</li>
                    <li className="flex items-center gap-3 text-sm font-medium text-gray-700"><History size={16} className="text-purple-500"/> Comprehensive Audit Trail</li>
                    <li className="flex items-center gap-3 text-sm font-medium text-gray-700"><ShieldCheck size={16} className="text-green-500"/> IT Act / ESIGN Compliant</li>
                  </ul>
                </div>
              </div>

              <div className="w-full md:w-2/3 flex flex-col h-full min-h-[400px]">
                
                {step === 2 && (
                  <div className="flex-grow flex flex-col animate-in fade-in">
                    <h3 className="text-xl font-bold text-gray-900 border-b pb-3 mb-6">Signer Identity & Protocol</h3>
                    
                    <div className="space-y-5">
                      <div>
                        <label className="block text-sm font-bold text-gray-700 mb-2">Legal Full Name</label>
                        <div className="relative">
                          <User size={18} className="absolute left-3 top-3.5 text-gray-400" />
                          <input type="text" value={signerName} onChange={(e) => setSignerName(e.target.value)} placeholder="e.g. Suhel Ansari" className="w-full border border-gray-300 rounded-lg p-3 pl-10 focus:ring-2 focus:ring-blue-500 outline-none" />
                        </div>
                      </div>
                      
                      <div>
                        <label className="block text-sm font-bold text-gray-700 mb-2">Email Address (For Audit Trail)</label>
                        <div className="relative">
                          <Mail size={18} className="absolute left-3 top-3.5 text-gray-400" />
                          <input type="email" value={signerEmail} onChange={(e) => setSignerEmail(e.target.value)} placeholder="email@company.com" className="w-full border border-gray-300 rounded-lg p-3 pl-10 focus:ring-2 focus:ring-blue-500 outline-none" />
                        </div>
                      </div>

                      <div className="bg-blue-50 border border-blue-100 p-4 rounded-xl mt-4">
                        <label className="flex items-start gap-3 cursor-pointer">
                          <input type="checkbox" checked={lockDocument} onChange={(e) => setLockDocument(e.target.checked)} className="mt-1 w-4 h-4 text-blue-600 rounded border-gray-300" />
                          <div>
                            <p className="text-sm font-bold text-gray-900">Lock Document with Tamper Seal</p>
                            <p className="text-xs text-gray-600 mt-1">Prevents anyone from editing the PDF after you sign it. If modified, the signature will instantly break and show as invalid.</p>
                          </div>
                        </label>
                      </div>
                    </div>

                    <button onClick={processSignature} className="mt-8 w-full flex items-center justify-center gap-2 px-8 py-4 rounded-xl text-white font-bold text-lg bg-[#E5322D] hover:bg-red-700 transition shadow-md">
                      Apply Cryptographic Signature <PenTool size={22} />
                    </button>
                  </div>
                )}

                {step === 3 && (
                  <div className="flex-grow flex flex-col">
                    <div className="flex justify-between items-center mb-3 border-b pb-2">
                      <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2"><Lock size={20} className="text-gray-700" /> Security Protocol Terminal</h3>
                      <span className="flex items-center gap-2 text-xs font-bold text-blue-600 animate-pulse"><Settings size={14} className="animate-spin" /> Signing...</span>
                    </div>
                    <div className="flex-grow bg-[#0D1117] rounded-xl p-5 overflow-y-auto shadow-inner font-mono text-[13px] leading-relaxed border border-gray-800">
                      {logs.map((log, index) => (
                        <div key={index} className={`mb-1 ${log.includes('[SUCCESS]') ? 'text-green-400' : log.includes('[FATAL') ? 'text-red-500' : log.includes('[PKI]') || log.includes('[HASH]') ? 'text-purple-400' : 'text-gray-300'}`}>
                          <span className="text-gray-500 mr-2">{new Date().toISOString().split('T')[1].split('.')[0]}</span>{log}
                        </div>
                      ))}
                      <div className="text-gray-500 animate-pulse mt-1">_</div>
                    </div>
                  </div>
                )}

                {step === 4 && (
                  <div className="flex-grow flex flex-col justify-center animate-in fade-in">
                    <div className="bg-green-50 border border-green-200 text-green-900 p-6 rounded-2xl flex flex-col items-center text-center gap-3 mb-6">
                      <CheckCircle2 size={50} className="text-green-500 mb-2" />
                      <h3 className="text-2xl font-bold">Document Signed & Sealed</h3>
                      <p className="text-sm">The cryptographic hash has been embedded. The document is legally binding and locked against future modifications.</p>
                    </div>
                    
                    <div className="flex flex-col gap-4 mt-2">
                      <a href={downloadUrl} download={`Signed_${file.name}`} className="w-full flex items-center justify-center gap-2 px-8 py-4 rounded-xl text-white font-bold text-lg bg-[#E5322D] hover:bg-red-700 transition shadow-lg">
                        <Download size={22} /> Download Signed PDF
                      </a>
                      <a href={auditLogUrl} download={`Audit_Trail_${file.name}.txt`} className="w-full flex items-center justify-center gap-2 px-8 py-4 rounded-xl text-gray-700 font-bold text-lg bg-white border-2 border-gray-200 hover:bg-gray-50 transition shadow-sm">
                        <History size={22} /> Download Audit Trail (Log)
                      </a>
                    </div>
                  </div>
                )}

              </div>
            </div>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
}
